package monoservice

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"sync"

	"github.com/alexflint/go-arg"
	"github.com/gorilla/mux"
	"github.com/teamwork/reload"
	"github.com/teejays/gokutil/client/db"
	client_file "github.com/teejays/gokutil/client/file"
	"github.com/teejays/gokutil/env"
	"github.com/teejays/gokutil/env/envutil"
	"github.com/teejays/gokutil/gopi"
	"github.com/teejays/gokutil/log"

	app_client "sampleapp/backend/.goku/generated/client"
	dbconn "sampleapp/backend/.goku/generated/dbconn"
	app_gokubuildinfo "sampleapp/backend/.goku/generated/gokubuildinfo"
	app_httproute "sampleapp/backend/.goku/generated/httproute"
	app_mthd "sampleapp/backend/.goku/generated/mthd"
	svccore_entfile_meta "sampleapp/backend/.goku/generated/service/core/entity/file/meta"
	svccore_entfile_typ "sampleapp/backend/.goku/generated/service/core/entity/file/typ"
	"sampleapp/backend/.goku/static/gateway"
	"sampleapp/backend/.goku/static/service/auth/auth"
	sttc_svccore_mthd "sampleapp/backend/.goku/static/service/core/mthd"
	"sampleapp/backend/.goku/static/service/user/userinit"
)

type Args struct {
	AppRootDir    string `arg:"-d,--app-root-dir" default:"." help:"The root directory of the goku generated app."`
	DevLiveReload bool   `arg:"-r,--dev-live-reload" default:"false" help:"Enable live reload in dev mode."`

	// HTTP Server options
	HTTPHost string `arg:"--http-host" default:"0.0.0.0" help:"The host to bind the HTTP server to."`
	HTTPPort int    `arg:"--http-port" default:"8080" help:"The port to bind the HTTP server to."`

	// GraphQL Server options
	GraphQLHost string `arg:"--graphql-host" default:"0.0.0.0" help:"The host to bind the GraphQL server to."`
	GraphQLPort int    `arg:"--graphql-port" default:"8081" help:"The port to bind the GraphQL server to."`

	// Common DB connection options.
	// If these values are specified, they will override the values specified in the app.yaml file or environment variables.
	CommonDbHost     string `arg:"--common-db-host" default:"localhost" help:"The host of the common database."`
	CommonDbPort     int    `arg:"--common-db-port" default:"5432" help:"The port of the common database."`
	CommonDbUser     string `arg:"--common-db-user" default:"goku" help:"The user of the common database."`
	CommonDbPassword string `arg:"--common-db-password" default:"goku" help:"The password of the common database."`
}

var _args Args

// Run is the main function that runs the monoservice
func Run(ctx context.Context) error {
	c, ctx, err := Initialize(ctx)
	if err != nil {
		return err
	}

	// Start the monoservice
	err = Start(ctx, c, StartOpts{
		StartGraphqlServer: true,
	})
	if err != nil {
		return err
	}

	return nil
}

func Initialize(ctx context.Context) (app_client.Client, context.Context, error) {
	var err error

	// Parse the args
	log.Debug(ctx, "Parsing command line args")

	err = arg.Parse(&_args)
	if err != nil {
		log.Warn(ctx, "Could not parse command line args", "error", err)
		arg.MustParse(&_args) // This command will print help message and exit
		return nil, ctx, err
	}
	log.Debug(ctx, "Command line args parsed", "args", _args)

	defer func() {
		if err != nil {
			arg.MustParse(&_args).WriteHelp(os.Stdout) // This command will print help message
		}
	}()

	log.Debug(ctx, "Running backend app generated by Goku", "version", app_gokubuildinfo.GokuVersionAtGenerate, "args", _args)

	// Ensure that app root dir has a `goku.yaml` file present
	f, err := os.Open(filepath.Join(_args.AppRootDir, "goku.yaml"))
	if err != nil {
		return nil, ctx, fmt.Errorf("Opening goku.yaml file: %w. Make sure the app-root-dir is set properly.", err)
	}
	defer f.Close()

	if _args.DevLiveReload {
		go func() {
			err := reload.Do(func(s string, i ...interface{}) {
				msg := fmt.Sprintf("[Reload]"+s, i...)
				log.Info(ctx, msg)
			})
			if err != nil {
				panic(err)
			}
		}()
	}

	// Load the env file
	err = envutil.LoadEnvFiles(ctx, _args.AppRootDir)
	if err != nil {
		return nil, ctx, fmt.Errorf("Loading env file: %w", err)
	}

	// Set some env vars so the rest of the app can use them
	err = os.Setenv("APP_ROOT_DIR", _args.AppRootDir)
	if err != nil {
		return nil, ctx, fmt.Errorf("Setting APP_ROOT_DIR env var: %w", err)
	}

	// Initialize the Database connection
	err = dbconn.InitDatabaseConnection(ctx, dbconn.AppInitConnectionRequest{
		Common: &db.ServiceInitConnectionRequest{
			Host:     _args.CommonDbHost,
			Port:     _args.CommonDbPort,
			User:     _args.CommonDbUser,
			Password: _args.CommonDbPassword,
		},
	})
	if err != nil {
		return nil, ctx, fmt.Errorf("Initializing Database connections: %w", err)
	}

	// Initialize the file client
	fileClient, err := client_file.NewLocalFileClient(ctx, filepath.Join(_args.AppRootDir, ".dev"))
	if err != nil {
		return nil, ctx, fmt.Errorf("constructing a new file client: %w", err)
	}

	err = client_file.InitDefaultFileClient(ctx, fileClient)
	if err != nil {
		return nil, ctx, fmt.Errorf("Initializing default file client: %w", err)
	}

	// Construct the Client
	c, err := app_mthd.NewClient(ctx)
	if err != nil {
		return c, ctx, fmt.Errorf("constructing a new client: %w", err)
	}

	// Set Static Hooks
	err = svccore_entfile_meta.GetTypeFileDALMeta().SetHookAddBefore(
		func(ctx context.Context, f svccore_entfile_typ.File) (svccore_entfile_typ.File, error) {
			return sttc_svccore_mthd.FileHookAddBefore(ctx, c, f)
		},
	)
	if err != nil {
		return c, ctx, fmt.Errorf("Setting BeforeCreateUpdateHook for [File] type: %w", err)
	}
	// Verify that the BeforeCreateUpdateHook is set
	if svccore_entfile_meta.GetTypeFileMeta().GetHookAddBefore() == nil {
		return c, ctx, fmt.Errorf("BeforeCreateUpdateHook for [File] type is not set")
	}

	return c, ctx, nil

}

type StartOpts struct {
	StartGraphqlServer bool
}

func Start(ctx context.Context, c app_client.Client, opts StartOpts) error {

	// Run any init functions
	if env.GetEnv() == env.DEV || env.GetEnv() == env.TEST {
		log.Info(ctx, "Upserting Dev User")
		err := userinit.UpsertDevUser(ctx, c)
		if err != nil {
			return fmt.Errorf("Running service [user] init logic: %w", err)
		}
	}

	// Get the Routes
	var routes = app_httproute.GetRoutes(ctx, c)

	// Middlewares
	authMiddlewareFunc, err := auth.GetAuthenticateHTTPMiddleware()
	if err != nil {
		return fmt.Errorf("constructing an AuthenticatorFunc: %w", err)
	}

	middlewares := gopi.MiddlewareFuncs{
		PreMiddlewares:  []mux.MiddlewareFunc{gopi.LoggerMiddleware},
		PostMiddlewares: []mux.MiddlewareFunc{gopi.SetJSONHeaderMiddleware, SetCorsAllowHeaderMiddleware},
		AuthMiddleware:  authMiddlewareFunc,
	}

	server, err := gopi.NewServer(ctx, routes, middlewares)
	if err != nil {
		return fmt.Errorf("constructing a new server: %w", err)
	}

	var wg sync.WaitGroup

	// Start the REST server
	wg.Add(1)
	go func() {
		defer wg.Done()
		var addr = _args.HTTPHost
		var port = _args.HTTPPort
		log.Info(ctx, "Starting HTTP server", "address", addr, "port", port)
		err := server.StartServer(ctx, addr, port)
		if err != nil {
			log.Error(ctx, "Could not start HTTP server", "error", err)
		}
	}()

	// Start Graphql Server
	if opts.StartGraphqlServer {
		wg.Add(1)
		go func() {
			defer wg.Done()
			var addr = _args.GraphQLHost
			var port = _args.GraphQLPort
			log.Info(ctx, "Starting Gateway (graphql) server", "address", addr, "port", port)
			err := gateway.StartServer(addr, port, filepath.Join(_args.AppRootDir, "backend/.goku/generated/graphql/schema.generated.graphql"))
			if err != nil {
				log.Error(ctx, "Could not start Gateway (graphql) server", "error", err)
			}
		}()
	}

	wg.Wait()

	return nil
}

func SetCorsAllowHeaderMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Set the header
		w.Header().Set("Access-Control-Allow-Origin", "*")
		// Call the next handler
		next.ServeHTTP(w, r)
	})
}
